import express from "express";
import path from "path";
import dotenv from "dotenv";
import helmet from "helmet";
import compression from "compression";
import morgan from "morgan";
import bodyParser from "body-parser";
import expressLayouts from "express-ejs-layouts";
import { fileURLToPath } from "url";
import cookieParser from "cookie-parser";
import authRouter from "./routes/auth.js";
import learnRouter from "./routes/learn.js";
import { attachUser, requireAuth } from "./middleware/auth.js";
import reviewRouter from "./routes/review.js";
import profileRouter from "./routes/profile.js";
import leaderboardRouter from "./routes/leaderboard.js";
import User from "./models/User.js";



// Import route files (we’ll create these next)
import questionsRouter from "./routes/questions.js";
import attemptsRouter from "./routes/attempts.js";
import lessonsRouter from "./routes/lessons.js";
import adminRouter from "./routes/admin.js";

// Basic setup
dotenv.config();
import mongoose from "mongoose";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// Connect to MongoDB
await mongoose.connect(process.env.MONGO_URL);

console.log("Connected to Mongo:", process.env.MONGO_URL);


// EJS template engine setup
app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "views"));
app.use(expressLayouts);   
app.set("layout", "layout");               // ← default layout is views/layout.ejs  
app.use(express.static(path.join(__dirname, "public")));

// Security & utilities
app.use(helmet({
  contentSecurityPolicy: {
    useDefaults: true,
    directives: {
      "default-src": ["'self'"],
      // Allow your local scripts + inline (for now) + MathJax CDN
      "script-src": ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net"],
      // Bootstrap CSS from CDN + any inline styles generated by libs
      "style-src": ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net"],
      // Allow fonts from your app, data URIs, and (optional) rokt/JSDelivr to quiet warnings
      "font-src": ["'self'", "data:", "https://cdn.jsdelivr.net", "https://apps.rokt.com"],
      // Images from your app or data URIs
      "img-src": ["'self'", "data:"],
      // Let the page fetch source maps / CDN assets if needed
      "connect-src": ["'self'", "https://cdn.jsdelivr.net", "https://apps.rokt.com", "https://apps-demo.rokt.com"],
      "object-src": ["'none'"]
    }
  }
}));
app.use(compression());
app.use(morgan("dev"));
app.use(bodyParser.json({ limit: "1mb" }));
app.use(bodyParser.urlencoded({ extended: true }));

app.use(cookieParser());
app.use(attachUser);
app.use((req, res, next) => { res.locals.user = req.user || null; next(); });

// Global 911 branding available in ALL EJS pages
app.use((req, res, next) => {
  res.locals.APP_NAME = "Quiz-911";
  res.locals.APP_TAGLINE = "911 Calltaker Procedures — Study Quiz";
  res.locals.APP_DISCLAIMER =
    "Study tool only. Not official guidance. Always follow your agency SOPs and current directives.";
  next();
});


app.get("/", (req, res) => res.render("home", { title: "911 Quiz" }));
app.use("/auth", authRouter);
app.use("/learn", learnRouter);
app.use("/review", reviewRouter);
// keep: /questions, /attempts, /lessons, /admin

app.use(async (req, res, next) => {
  if (req.user?.id) {
    const u = await User.findById(req.user.id).select("displayName email xp streak").lean();
    if (u) {
      req.user = { ...req.user, ...u };   // keep id/email from JWT, add xp/streak from DB
    }
  }
  res.locals.user = req.user || null;     // EJS can use "user"
  next();
});

// Routes
app.get("/", (req, res) => res.render("home", { title: "911 Quiz" }));
app.use("/questions", questionsRouter);
app.use("/attempts", attemptsRouter);
app.use("/lessons", lessonsRouter);
app.use("/admin", adminRouter);
app.get("/auth/login", (req,res)=> res.render("auth_login", { title: "Login" }));
app.use("/auth", authRouter);
app.use("/profile", profileRouter);
app.use("/leaderboard", leaderboardRouter);

// protect learn + lessons if you want:
app.get("/learn", requireAuth, async (req,res,next)=> next()); // the /learn route will be defined below

// Start server
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`🚀 Server running at http://localhost:${port}`));
